# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.twitter_services:
        class: AppBundle\Services\TwitterServices
        arguments: ["@doctrine.orm.entity_manager", "@endroid.twitter", "@logger"]
